// Step 13.4 — every route the application mounts declares a rate-limit bucket (SYS-012, D-026,
// 10-backend-spec.md §4).
//
// The direction matters. A test that walked the routes which *have* a bucket and checked their
// buckets were valid would pass on the day somebody adds a route with none — which is the only
// failure this file exists to catch. So it is written the other way round: the route files on disk
// are the input, the declared bucket is the thing that may be missing, and anything missing that is
// not on a short, justified exemption list is a failure by name.
//
// Two kinds of gap count as missing, because both are ways an endpoint reaches production
// unlimited: a handler with no route spec at all (nothing declared it, so nothing can read it), and
// a spec whose `rateLimit` is absent. Two routes were the first kind when this file was written —
// `POST /runs/{runId}/delegations`, which enforced the `llm` bucket by hand, and
// `POST /test/runs/{runId}/advance-clock`, which enforced `write` through a wrapped handler. Both
// carried no spec so the OpenAPI generator would not describe them, and the cost of saying it that
// way was that the sweep could not see them either (D-613).
import { readdirSync, statSync } from 'node:fs'
import { join, resolve, sep } from 'node:path'
import { pathToFileURL } from 'node:url'
import { describe, expect, it } from 'vitest'
import { z } from 'zod'
import { getRouteSpec, type RegisteredRoute } from '@/server/http/openapi-registry'
import { RATE_LIMITS, type RateLimitBucket } from '@/server/rate-limit/limits'

const API_ROOT = resolve('src/app/api')
const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const

type Mounted = {
  /** `/api/v1/runs/[runId]/claims`, as Next mounts it. */
  url: string
  method: (typeof METHODS)[number]
  spec: RegisteredRoute | undefined
}

/**
 * Routes exempted by build-plan phase-13 §13.4, by the path each is mounted at.
 *
 * `/api/health` and `/api/ready` are the uptime probes of 13 §4: a probe that can be rate limited
 * is a probe that reports an outage it caused. `/api/internal/jobs/drain` is called by Vercel Cron
 * and by an operator, both behind `CRON_SECRET` — a bearer token is the limit.
 *
 * `/api/openapi` is listed and does not exist: `docs/tech/openapi.yaml` is a file in the
 * repository, generated by `pnpm openapi:generate`, not an endpoint. It stays on the list so that
 * mounting one later is an exemption somebody chose; the assertion below pins the fact that it is
 * the *only* unused entry, so the list cannot quietly rot into permission for anything else.
 */
const EXEMPT_PATHS = [
  '/api/health',
  '/api/ready',
  '/api/openapi',
  '/api/internal/jobs/drain',
] as const

/** Exempt paths this build does not mount. Exactly one, and adding the route removes it. */
const EXEMPT_PATHS_NOT_MOUNTED = ['/api/openapi']

/**
 * The one handler in the tree that legitimately declares nothing: Better Auth's own mount point.
 *
 * It is not a `defineRoute` route and cannot be — the library owns the request handling for
 * sign-in, sign-up, verification, reset, the Google callback and the organization endpoints (08
 * §1). Its limiter is its own, and the assertion below reads that configuration rather than taking
 * the exemption on trust.
 */
const UNSPECIFIED_PATHS = ['/api/auth/[...all]']

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, out)
    else if (entry === 'route.ts') out.push(full)
  }
  return out
}

/** src/app/api/v1/runs/[runId]/route.ts → /api/v1/runs/[runId] (route groups dropped). */
function urlFromFile(file: string): string {
  const rel = file
    .split(sep)
    .join('/')
    .slice(resolve('src/app').split(sep).join('/').length)
    .replace(/\/route\.ts$/, '')
  return rel
    .split('/')
    .filter((segment) => segment && !/^\(.*\)$/.test(segment))
    .reduce((acc, segment) => `${acc}/${segment}`, '')
}

async function mountedRoutes(): Promise<Mounted[]> {
  const out: Mounted[] = []
  for (const file of walk(API_ROOT)) {
    const mod = (await import(pathToFileURL(file).href)) as Record<string, unknown>
    const url = urlFromFile(file)
    for (const method of METHODS) {
      if (!(method in mod)) continue
      out.push({ url, method, spec: getRouteSpec(mod[method]) })
    }
  }
  return out
}

const BUCKETS = new Set(Object.keys(RATE_LIMITS))

/**
 * Every mounted handler that declares no bucket and is not exempt, as one readable line each.
 *
 * Extracted so the assertions below can be fed a route list this file makes up as well as the real
 * one — which is how the sweep is proven to bite (`it('reports a new route …')`).
 */
function unlimited(routes: readonly Mounted[]): string[] {
  return routes
    .filter((route) => !EXEMPT_PATHS.some((path) => route.url === path))
    .filter((route) => !UNSPECIFIED_PATHS.includes(route.url))
    .filter((route) => route.spec?.rateLimit === undefined)
    .map(
      (route) =>
        `${route.method} ${route.url} (${route.spec ? `operationId ${route.spec.operationId}, no rateLimit` : 'no route spec at all'})`,
    )
    .sort()
}

const routes = await mountedRoutes()

describe('every route declares a rate-limit bucket', () => {
  it('found the API tree: this suite is reading real route files', () => {
    // The control. A walk that resolved nothing would make every assertion below vacuously true,
    // and the failure would look exactly like success.
    expect(routes.length).toBeGreaterThan(100)
    expect(routes.map((route) => `${route.method} ${route.url}`)).toContain(
      'GET /api/v1/runs/[runId]',
    )
    expect(routes.filter((route) => route.spec !== undefined).length).toBeGreaterThan(100)
  })

  it('leaves no route unlimited', () => {
    expect(unlimited(routes)).toEqual([])
  })

  it('reports a new route that forgot one, and one that declared nothing at all', () => {
    // The same function, over a list this test invents: a spec with no `rateLimit`, and a handler
    // with no spec. Both are ways an endpoint ships unlimited, and both must be named.
    const invented: Mounted[] = [
      {
        url: '/api/v1/runs/[runId]/something-new',
        method: 'POST',
        spec: {
          operationId: 'somethingNew',
          summary: 'A route added without a bucket',
          tags: ['runs'],
          status: 200,
          auth: 'session',
          output: z.object({}),
        },
      },
      { url: '/api/v1/runs/[runId]/hand-written', method: 'POST', spec: undefined },
    ]

    expect(unlimited(invented)).toEqual([
      'POST /api/v1/runs/[runId]/hand-written (no route spec at all)',
      'POST /api/v1/runs/[runId]/something-new (operationId somethingNew, no rateLimit)',
    ])
    // And an exempt path stays exempt whatever it declares.
    expect(unlimited([{ url: '/api/health', method: 'GET', spec: undefined }])).toEqual([])
  })

  it('declares only buckets 10 §4 defines', () => {
    const declared = new Set(
      routes
        .map((route) => route.spec?.rateLimit)
        .filter((b): b is RateLimitBucket => b !== undefined),
    )
    expect(declared.size).toBeGreaterThan(0)
    for (const bucket of declared) expect(BUCKETS).toContain(bucket)
    // Every bucket 10 §4 sizes is actually used by something: a bucket nothing declares is either a
    // limit that was dropped or a route group that lost its limit.
    expect([...declared].sort()).toEqual([...BUCKETS].sort())
  })

  it('declares the two routes that are deliberately absent from OpenAPI (D-613)', () => {
    // The two this sweep could not see before. `documented: false` is what lets them declare a
    // bucket without the generator describing them: the delegation stream answers
    // `text/event-stream`, which openapi.yaml states by hand (D-273), and the clock control exists
    // only under APP_ENV=test and must never appear in the document at all (D-109).
    const at = (url: string) =>
      routes.find((route) => route.url === url && route.method === 'POST')?.spec

    expect(at('/api/v1/runs/[runId]/delegations')).toMatchObject({
      operationId: 'delegate',
      rateLimit: 'llm',
      documented: false,
    })
    expect(at('/api/v1/test/runs/[runId]/advance-clock')).toMatchObject({
      operationId: 'advanceRunClock',
      rateLimit: 'write',
      documented: false,
    })
    // And `documented: false` means exactly that: neither operation is in the committed document
    // as a generated one. (`openapi:check` is the other half; this is the reason it stays green.)
    expect(routes.filter((route) => route.spec?.documented === false)).toHaveLength(2)
  })
})

describe('the exemptions', () => {
  it('are used, and only the one route this build does not mount is unused', () => {
    const mounted = new Set(routes.map((route) => route.url))
    const unused = EXEMPT_PATHS.filter((path) => !mounted.has(path))
    expect(unused).toEqual(EXEMPT_PATHS_NOT_MOUNTED)
  })

  it('cover nothing a session can reach: a probe or a cron secret, never a user', () => {
    for (const route of routes.filter((r) => EXEMPT_PATHS.some((path) => r.url === path))) {
      // `public` for the two probes, `cron` for the drain. An exempt route that took a session
      // would be an authenticated endpoint with no limit, which is what SYS-012 forbids.
      expect([route.url, route.spec?.auth]).not.toEqual([route.url, 'session'])
      expect(['public', 'cron']).toContain(route.spec?.auth)
    }
  })

  it('let Better Auth’s mount point through only because Better Auth limits it itself', async () => {
    const { auth } = await import('@/server/auth/auth')
    const { rateLimit } = auth.options

    expect(rateLimit?.enabled).toBe(true)
    expect(rateLimit?.max).toBeGreaterThan(0)
    expect(rateLimit?.window).toBeGreaterThan(0)
    // 08 §2.6: ten a minute per IP on the four endpoints an attacker would grind.
    expect(rateLimit?.customRules).toMatchObject({
      '/sign-in/email': { window: 60, max: 10 },
      '/sign-up/email': { window: 60, max: 10 },
      '/request-password-reset': { window: 60, max: 10 },
      '/send-verification-email': { window: 60, max: 10 },
    })
  })

  it('is the only handler in the tree with no spec', () => {
    const unspecified = routes
      .filter((route) => route.spec === undefined)
      .map((route) => route.url)
      .filter((url, index, all) => all.indexOf(url) === index)
    expect(unspecified).toEqual(UNSPECIFIED_PATHS)
  })
})
