// Every Drizzle schema file is re-exported here; `drizzle.config.ts` and the db client read this
// module (docs/tech/06-data-model.md §1). ./auth.ts is generated by `npx auth generate` (D-099) and
// never edited by hand; the remaining files arrive with Phase 2 steps 2.2–2.5.
export * from './auth'
