// Every Drizzle schema file is re-exported here; `drizzle.config.ts` and the db client read this
// module (docs/tech/06-data-model.md §1). ./auth.ts is generated by `npx auth generate` (D-099) and
// never edited by hand. Files are added step by step so each Phase 2 step owns one migration.
export * from './auth'
export * from './enums'
export * from './tenancy'
export * from './courses'
export * from './scenarios'
export * from './authoring'
export * from './runs'
