// Public interface of the `courses` module (docs/tech/10-backend-spec-modules.md §3).
// Other modules, Server Components, and job handlers import from here; never from ./service,
// ./repository, or ./errors.
export {
  addSectionMember,
  changeMapping,
  createAssignment,
  createCourse,
  createSection,
  deleteWalkthroughRun,
  getAssignment,
  getCourse,
  getPolicyDisplay,
  listAssignmentRuns,
  listConfirmedPackageVersions,
  listCourses,
  listMyAssignments,
  listSectionMembers,
  previewMappingChange,
  recomputeExports,
  removeSectionMember,
  updateAssignment,
  updateCoursePolicy,
} from './service'

export type {
  AddSectionMemberInput,
  Assignment,
  AssignmentView,
  ChangeMappingInput,
  ConfirmedPackageVersion,
  Course,
  CourseSummary,
  CourseView,
  CreateAssignmentInput,
  CreateCourseInput,
  CreateSectionInput,
  Mapping,
  MappingChangePreview,
  MappingChangeRow,
  OutsideAiPolicy,
  PageQuery,
  PolicyDisplay,
  PreviewMappingChangeInput,
  RunTypeValue,
  Section,
  SectionMember,
  SectionRoleValue,
  SectionSummary,
  StudentAssignment,
  UpdateAssignmentInput,
  UpdateCoursePolicyInput,
} from './schema'
