// One example payload per catalogue event: docs/tech/17-analytics-events.md §9.1.
// The mapped type makes a missing example a compile error, so adding an event to `EVENTS` without
// adding it here does not build — which is the point: an event with no example is an event nobody
// has checked the shape of.
import type { EventName, EventProps } from '@/lib/analytics/events'

const R = {
  run_id: '11111111-1111-4111-8111-111111111111',
  assignment_id: '22222222-2222-4222-8222-222222222222',
  package_version_id: '33333333-3333-4333-8333-333333333333',
  variant: 'defective',
  mode: 'standard',
  attempt_no: 1,
  is_walkthrough: true,
} as const
const P = {
  package_id: '44444444-4444-4444-8444-444444444444',
  package_version_id: R.package_version_id,
  version: 1,
} as const
const C = {
  claim_id: '55555555-5555-4555-8555-555555555555',
  importance: 'load_bearing',
  consequence_level: 'high',
  in_turn_window: false,
} as const
const U = '66666666-6666-4666-8666-666666666666'

export const eventExamples: { [E in EventName]: EventProps<E> } = {
  // AN-002 activation
  sign_up_completed: { method: 'password' },
  email_verified: { ms_since_sign_up: 120000 },
  sign_in_succeeded: { method: 'google' },
  invitation_accepted: { invitation_id: U, role: 'student', ms_since_invited: 3600000 },
  course_created: {
    course_id: U,
    outside_ai_policy: 'declared',
    mapping_is_default: true,
    ms_since_first_sign_in: 600000,
  },
  assignment_configured: {
    assignment_id: R.assignment_id,
    course_id: U,
    section_id: U,
    package_version_id: R.package_version_id,
    variant: 'sound',
    is_new: true,
    is_walkthrough: true,
    working_clock_seconds: 1500,
    weight_overridden: false,
    ms_since_first_sign_in: 900000,
  },
  policy_displayed: {
    ...R,
    outside_ai_policy: 'declared',
    weight_percent: 2.5,
    mapping_is_default: true,
  },
  run_started: { ...R, is_reoffer: false, run_index_for_student: 1 },

  // AN-001 authoring measures
  package_created_from_seed: { ...P, seed_chars: 48000, concept_count: 6 },
  generation_step_completed: {
    ...P,
    generation_run_id: U,
    step: 'claims_and_states',
    pass_number: 2,
    status: 'succeeded',
    duration_ms: 42000,
    failed_rules: ['DEFECT_NOT_CONSEQUENTIAL'],
    input_tokens: 12000,
    output_tokens: 3000,
    provider: 'mock',
  },
  element_decided: {
    ...P,
    element_type: 'claim',
    revision: 1,
    decision: 'edited',
    review_ms: 95000,
    edited_fields_count: 2,
  },
  package_confirmed: {
    ...P,
    seed_to_confirmed_ms: 7200000,
    edit_rate: 0.31,
    rejected_share: 0.08,
    generation_passes: 9,
    generation_max_pass: 2,
    elements_count: 52,
    review_ms_total: 5400000,
    review_ms_per_element: 103846,
    claims_count: 8,
    documents_count: 9,
  },

  // AN-003 engagement
  readiness_submitted: {
    ...R,
    skipped: false,
    expired: false,
    answered_count: 16,
    held_count: 5,
    not_held_count: 1,
    unknown_count: 0,
    duration_ms: 420000,
  },
  document_opened: {
    ...R,
    document_id: U,
    document_role: 'superseded',
    open_index: 3,
    before_first_delegation: true,
    in_turn_window: false,
    skim: false,
    duration_ms: 48000,
  },
  frame_locked: {
    ...R,
    confidence: 60,
    ms_since_room_opened: 300000,
    documents_opened_count: 4,
    words_total: 110,
  },
  delegation_made: {
    ...R,
    delegation_id: U,
    seq: 1,
    claims_surfaced: 2,
    in_turn_window: false,
    unverified_numbers_count: 0,
    failed: false,
    has_why: true,
    latency_ms: 1800,
    before_any_document_open: false,
  },
  claim_marked_used: { ...R, ...C, via: 'named_field' },
  stance_set: {
    ...R,
    ...C,
    stance: 'verify',
    previous_stance: 'accept',
    had_prior_action: true,
    is_change: true,
    ms_since_surfaced: 90000,
  },
  action_run: {
    ...R,
    ...C,
    action_id: U,
    type: 'source_trace',
    clock_cost_ms: 60000,
    clock_remaining_ms: 840000,
  },
  escalation_made: {
    ...R,
    ...C,
    escalation_id: U,
    response_kind: 'claim',
    counts_against_limit: true,
    clock_cost_ms: 300000,
  },
  probe_fired: { ...R, claim_id: C.claim_id },
  outside_tool_declared: { ...R, course_policy: 'declared' },
  lock_refused: {
    ...R,
    claim_id: C.claim_id,
    unstanced_relied_on_count: 1,
    clock_remaining_ms: 120000,
  },
  decision_locked: {
    ...R,
    auto_locked: false,
    speed_outlier: false,
    elapsed_ms: 1320000,
    confidence: 70,
    relied_on_count: 4,
    unstanced_count: 0,
    empty_fields_count: 0,
    clock_remaining_ms: 180000,
  },
  addendum_added: { ...R, ms_since_lock: 30000 },
  run_paused: { ...R, pause_id: U, cause: 'assistant_failure', forced_by_test_control: true },
  run_resumed: { ...R, pause_id: U, paused_ms: 12000, credited_ms: 0 },
  turn_delivered: { ...R, lag_ms: 2100, delivered_offline: false },
  turn_response_locked: {
    ...R,
    response: 'revise',
    implicit: false,
    confidence: 55,
    ms_since_delivered: 400000,
    window_claims_count: 1,
  },
  defense_completed: {
    ...R,
    questions_count: 7,
    follow_ups_count: 2,
    answered_count: 9,
    duration_ms: 780000,
    nothing_answered: false,
  },
  debrief_opened: { ...R, bands_status: 'draft', first_open: true, ms_since_scored: 60000 },
  debrief_answered: { ...R, ms_since_first_open: 600000 },
  record_opened: { ...R, viewer: 'owner' },

  // AN-004 faculty review
  replay_opened: { ...R, first_open: true, scoring_status: 'done' },
  band_decided: {
    ...R,
    dimension: 'calibration',
    decision: 'overridden',
    draft_status: 'drafted',
    changed_from_draft: true,
    has_note: true,
    ms_since_replay_opened: 240000,
  },
  run_confirmed: {
    ...R,
    review_duration_ms: 660000,
    override_count: 1,
    unassessed_count: 0,
    points_present: true,
    ms_since_scored: 3600000,
  },
  export_written: { ...R, export_id: U, version: 1, reason: 'initial' },
  claim_neutralized: {
    ...R,
    claim_id: C.claim_id,
    reason: 'unintended_defect',
    credit_challenge: true,
    dimensions_recomputed: 2,
    bands_raised_count: 1,
    review_requested: true,
  },
  run_voided: { ...R, state_at_void: 'decision_locked', reason: 'walkthrough' },
  run_reoffered: { ...R, attempt_no: 2, from_run_id: U, same_variant: false },

  // AN-005 per-run measures
  run_scored: {
    ...R,
    false_challenge_rate: 0.7273,
    matched_stance_share: 0.5,
    accept_share: 0.25,
    unassessed_count: 0,
    provisional_count: 5,
    scoring_latency_ms: 4200,
    rubric_version: 'v1',
    provider: 'mock',
    consequential_claims_count: 8,
    surfaced_claims_count: 6,
    delegations_count: 3,
    actions_count: 2,
    escalations_count: 1,
    documents_opened_count: 5,
    duration_ms: 2400000,
    confidence_at_frame: 60,
    confidence_at_lock: 70,
    confidence_after_turn: 55,
    accuracy_at_lock: 0.75,
    band_framing: 'proficient',
    band_delegation: 'developing',
    band_verification: 'developing',
    band_calibration: 'novice',
    band_decision_quality: 'proficient',
    band_adaptation: 'proficient',
    band_ownership: 'developing',
    all_novice: false,
    all_professional: false,
    held: false,
  },

  // operations
  llm_call: {
    feature: 'band_read',
    prompt: 'band-read-framing',
    version: 1,
    provider: 'mock',
    model: 'mock-v1',
    outcome: 'ok',
    latency_ms: 12,
    input_tokens: 900,
    output_tokens: 120,
    cost_usd: 0,
    fallback_used: false,
    run_id: R.run_id,
    package_version_id: null,
  },
  rate_limited: { bucket: 'run_events', scope: 'user' },
  error_shown: { code: 'LOCK_REFUSED_UNSTANCED_CLAIM', status: 409, route: '/runs/[runId]/work' },
}
